services:
  - type: web
    name: holerite-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npx ts-node server/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
